# Generated by Django 4.2.3 on 2023-07-03 12:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('town', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('contact_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cargo_weight', models.PositiveSmallIntegerField(default='Whole cargo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.CreateModel(
            name='LoadPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('town', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=64)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('contact_number', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('trailer_type', models.CharField(choices=[('Curtain-side trailer', 'Curtain Side'), ('Refrigerated trailer', 'Refrigerated'), ('Tipper trailer', 'Tipper'), ('Low-loader trailer', 'Low Loader'), ('Container trailer', 'Container'), ('Self-unloading trailer', 'Self Unloading'), ('Tanker trailer', 'Tanker'), ('Insulated trailer', 'Insulated')], max_length=64)),
                ('load_weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistician_app.delivery')),
                ('load_place', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='logistician_app.loadplace')),
            ],
        ),
    ]
