# Generated by Django 4.2.3 on 2023-07-04 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistician_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankerTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber_1', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(7100)])),
                ('chamber_2', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(9600)])),
                ('chamber_3', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(3700)])),
                ('chamber_4', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(6200)])),
                ('chamber_5', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(11500)])),
            ],
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='tanker_trailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='trailer_type',
            field=models.CharField(choices=[('Curtain-side trailer', 'Curtain Side'), ('Refrigerated trailer', 'Refrigerated'), ('Tipper trailer', 'Tipper'), ('Low-loader trailer', 'Low Loader'), ('Container trailer', 'Container'), ('Self-unloading trailer', 'Self Unloading'), ('Insulated trailer', 'Insulated')], max_length=64),
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='tanker_volume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistician_app.tankertrailer'),
        ),
    ]
