# Generated by Django 4.2.3 on 2023-07-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistician_app', '0002_remove_transportationorder_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='transportation_order',
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='logistician_app.delivery'),
            preserve_default=False,
        ),
    ]
