# Generated by Django 4.2.3 on 2023-07-03 15:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistician_app', '0004_remove_transportationorder_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='transportation_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='logistician_app.transportationorder'),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='load_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportation_order', to='logistician_app.loadplace'),
        ),
    ]
